### ISSUE TITLE
Add balupton as maintainer

### ISSUE THREAD

**Issue by balupton** [docpad/docpad-plugin-gist#2]
Hey @georgeOsdDev

Can you please add me as a maintainer so I can keep this plugin up to date with the latest docpad releases? `npm owner add balupton docpad-plugin-gist` is what you'll need to run.

Cheers!

**Comment by balupton** [comment]
hi @georgeOsdDev, seems npm has multiple levels of owner,

can you run `npm owner add bevryme docpad-plugin-gist` please

**Comment by georgeOsdDev** [comment]
@balupton 

```
oshidatakeharu at oshida in ~
$ npm owner add bevryme docpad-plugin-gist
+ bevryme (docpad-plugin-gist)

oshidatakeharu at oshida in ~
$ npm owner add bevryme docpad-plugin-uglify
+ bevryme (docpad-plugin-uglify)
```

**Comment by balupton** [comment]
Perfect, thank you!
